default_config:

logger:
  default: warning
  logs:
    custom_components.airport_hamburg: debug
lovelace:
  resources:
    - url: https://cdn.jsdelivr.net/gh/custom-cards/flex-table-card@master/flex-table-card.js
      type: module